# FPGA_CLK 时钟引脚
set_property PACKAGE_PIN W19 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
# RESET 复位引脚
set_property PACKAGE_PIN Y19 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
# 串口引脚约束
set_property PACKAGE_PIN W17 [get_ports in]
set_property IOSTANDARD LVCMOS33 [get_ports in]
set_property PACKAGE_PIN V17 [get_ports out]
set_property IOSTANDARD LVCMOS33 [get_ports out]
# 位选信号约束
set_property PACKAGE_PIN K18 [get_ports dig[5]]
set_property IOSTANDARD LVCMOS33 [get_ports dig[5]]
set_property PACKAGE_PIN K16 [get_ports dig[4]]
set_property IOSTANDARD LVCMOS33 [get_ports dig[4]]
set_property PACKAGE_PIN L16 [get_ports dig[3]]
set_property IOSTANDARD LVCMOS33 [get_ports dig[3]]
set_property PACKAGE_PIN G20 [get_ports dig[2]]
set_property IOSTANDARD LVCMOS33 [get_ports dig[2]]
set_property PACKAGE_PIN H20 [get_ports dig[1]]
set_property IOSTANDARD LVCMOS33 [get_ports dig[1]]
set_property PACKAGE_PIN H18 [get_ports dig[0]]
set_property IOSTANDARD LVCMOS33 [get_ports dig[0]]
# 输出引脚约束
set_property PACKAGE_PIN U22 [get_ports led_out[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led_out[0]]
set_property PACKAGE_PIN P19 [get_ports led_out[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led_out[1]]
set_property PACKAGE_PIN W21 [get_ports led_out[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led_out[2]]
set_property PACKAGE_PIN V22 [get_ports led_out[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led_out[3]]
set_property PACKAGE_PIN AB20 [get_ports led_out[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led_out[4]]
set_property PACKAGE_PIN W22 [get_ports led_out[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led_out[5]]
set_property PACKAGE_PIN AA20 [get_ports led_out[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led_out[6]]
